"""Sitemap discovery and parsing.

The largest single efficiency gain available to a spider, and it is not close.
Discovering ten thousand URLs by following links costs ten thousand fetches
and parses; reading them out of a sitemap index costs half a dozen
(docs/05_SPIDER_ARCHITECTURE.md).

**robots.txt is read, not obeyed.** This tool does not enforce robots rules
(docs/17_NON_GOALS.md), but the file is still the canonical place a site says
where its sitemaps are. Parsing it for ``Sitemap:`` and ignoring everything
else is not inconsistent - it is using a directory without following the
instructions in it.

**``<lastmod>`` is carried through.** It is what makes an incremental recrawl
possible later (Phase 11): a sitemap that says nothing changed since the last
run turns a full crawl into a handful of fetches.

Parsing is defensive throughout. Sitemaps are generated by whatever plugin the
site happens to run, and a malformed one should cost the sitemap, not the
crawl.
"""

from __future__ import annotations

import gzip
import re
from dataclasses import dataclass
from datetime import UTC, datetime
from xml.etree import ElementTree

from crwallm.policy.url import NormalizedUrl, UrlNormalizationError, normalize

__all__ = [
    "SitemapEntry",
    "SitemapParseResult",
    "candidate_sitemap_urls",
    "parse_robots_txt",
    "parse_sitemap",
]

MAX_ENTRIES = 50_000
"""Per document. The sitemap spec caps at this, and a file claiming more is
either broken or hostile - either way not worth the memory."""

MAX_INDEX_DEPTH = 3
"""A sitemap index may point at further indexes. Three levels is deeper than
any real site goes; beyond that it is a loop."""

_SITEMAP_DIRECTIVE = re.compile(r"^\s*sitemap\s*:\s*(\S+)", re.IGNORECASE | re.MULTILINE)

# Sitemaps are namespaced, inconsistently. Matching on the local tag name
# avoids caring which namespace URI a generator picked.
_LOCAL = re.compile(r"\{.*\}")


def _tag(element: ElementTree.Element) -> str:
    return _LOCAL.sub("", element.tag).lower()


@dataclass(frozen=True, slots=True)
class SitemapEntry:
    url: NormalizedUrl
    lastmod: datetime | None = None
    priority: float | None = None
    changefreq: str | None = None

    @property
    def is_index(self) -> bool:
        return False


@dataclass(frozen=True, slots=True)
class SitemapParseResult:
    """What one sitemap document contained."""

    entries: tuple[SitemapEntry, ...] = ()
    nested: tuple[str, ...] = ()
    """URLs of further sitemaps, when this was an index."""

    error: str | None = None

    @property
    def is_index(self) -> bool:
        return bool(self.nested) and not self.entries


def parse_robots_txt(text: str, *, base_url: str) -> tuple[str, ...]:
    """Extract ``Sitemap:`` directives. Everything else is ignored.

    Deliberately: the rules in robots.txt are not enforced here
    (docs/11_SECURITY_MODEL.md section 9), but the sitemap pointers are the
    only reliable way to find a sitemap that is not at the conventional path.
    """
    found: list[str] = []
    seen: set[str] = set()
    for match in _SITEMAP_DIRECTIVE.finditer(text):
        raw = match.group(1).strip()
        try:
            resolved = normalize(raw, base=base_url).url
        except UrlNormalizationError:
            continue
        if resolved not in seen:
            seen.add(resolved)
            found.append(resolved)
    return tuple(found)


def candidate_sitemap_urls(base_url: str) -> tuple[str, ...]:
    """Where to look when robots.txt says nothing.

    Ordered by how often each actually holds one. Every miss is a wasted
    request, so the list stays short.
    """
    try:
        root = normalize(base_url)
    except UrlNormalizationError:
        return ()
    origin = f"{root.scheme}://{root.host_port}"
    return (
        f"{origin}/sitemap.xml",
        f"{origin}/sitemap_index.xml",
        f"{origin}/sitemap-index.xml",
        f"{origin}/sitemap.xml.gz",
    )


def _decompress(body: bytes) -> bytes:
    """Sitemaps are frequently gzipped, sometimes without saying so."""
    if body[:2] == b"\x1f\x8b":
        try:
            return gzip.decompress(body)
        except (OSError, EOFError):
            return body
    return body


def _parse_lastmod(value: str | None) -> datetime | None:
    """W3C datetime, in whichever of its forms the generator chose.

    Returned timezone-aware: a naive value compared against an aware one
    raises, and both spellings appear in the wild.
    """
    if not value:
        return None
    text = value.strip()
    try:
        parsed = datetime.fromisoformat(text.replace("Z", "+00:00"))
    except ValueError:
        for fmt in ("%Y-%m-%d", "%Y-%m", "%Y"):
            try:
                parsed = datetime.strptime(text, fmt)
                break
            except ValueError:
                continue
        else:
            return None
    return parsed if parsed.tzinfo else parsed.replace(tzinfo=UTC)


def _parse_priority(value: str | None) -> float | None:
    if not value:
        return None
    try:
        return min(max(float(value.strip()), 0.0), 1.0)
    except ValueError:
        return None


def parse_sitemap(
    body: bytes,
    *,
    base_url: str,
    dedupe_whitelist: frozenset[str] | None = None,
    max_entries: int = MAX_ENTRIES,
) -> SitemapParseResult:
    """Parse one sitemap or sitemap index.

    Never raises. A site's sitemap is generated by whatever plugin it happens
    to run, and a broken one should cost the sitemap rather than the crawl -
    the caller falls back to following links.
    """
    raw = _decompress(body)
    if not raw.strip():
        return SitemapParseResult(error="empty document")

    try:
        # ElementTree resolves no external entities and expands no parameter
        # entities, so an XXE payload in a sitemap is inert. Worth stating,
        # because "parse XML from an untrusted source" usually is not.
        root = ElementTree.fromstring(raw)  # noqa: S314 - see above
    except ElementTree.ParseError as exc:
        return SitemapParseResult(error=f"malformed XML: {exc}")

    kind = _tag(root)
    entries: list[SitemapEntry] = []
    nested: list[str] = []

    for child in root:
        if len(entries) + len(nested) >= max_entries:
            break

        child_tag = _tag(child)
        if child_tag not in ("url", "sitemap"):
            continue

        values: dict[str, str] = {}
        for field in child:
            text = (field.text or "").strip()
            if text:
                values[_tag(field)] = text

        location = values.get("loc")
        if not location:
            continue

        if child_tag == "sitemap" or kind == "sitemapindex":
            try:
                nested.append(normalize(location, base=base_url).url)
            except UrlNormalizationError:
                continue
            continue

        try:
            url = normalize(location, base=base_url, dedupe_whitelist=dedupe_whitelist)
        except UrlNormalizationError:
            continue

        entries.append(
            SitemapEntry(
                url=url,
                lastmod=_parse_lastmod(values.get("lastmod")),
                priority=_parse_priority(values.get("priority")),
                changefreq=values.get("changefreq"),
            )
        )

    if not entries and not nested:
        return SitemapParseResult(error=f"no <url> or <sitemap> entries in <{kind}>")
    return SitemapParseResult(entries=tuple(entries), nested=tuple(nested))
