"""Phase 2 schema: specs, jobs, results, records, events.

Revision ID: 0001
Revises:
Create Date: Phase 2

Written by hand rather than autogenerated - autogenerate needs a live database
to diff against, and the first migration has nothing to diff. Verified with
``alembic upgrade head && alembic check``, which fails if the result does not
match ``Base.metadata``.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "crawl_specs",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crawl_specs")),
    )

    op.create_table(
        "crawl_jobs",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("spec_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=100), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pages_crawled", sa.Integer(), nullable=False),
        sa.Column("pages_failed", sa.Integer(), nullable=False),
        sa.Column("records_extracted", sa.Integer(), nullable=False),
        sa.Column("error_kind", sa.String(length=40), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reject_counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('queued','running','completed','failed','cancelled')",
            name=op.f("ck_crawl_jobs_status_known"),
        ),
        sa.ForeignKeyConstraint(
            ["spec_id"],
            ["crawl_specs.id"],
            name=op.f("fk_crawl_jobs_spec_id_crawl_specs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crawl_jobs")),
    )
    # The claim query: queued rows, highest priority first, oldest first.
    op.create_index("ix_crawl_jobs_claim", "crawl_jobs", ["status", "priority", "created_at"])

    op.create_table(
        "crawl_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["crawl_jobs.id"],
            name=op.f("fk_crawl_events_job_id_crawl_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crawl_events")),
    )
    # (job_id, id) rather than job_id alone: id is the SSE cursor, so replay
    # from Last-Event-ID is an index range scan.
    op.create_index("ix_crawl_events_job_id", "crawl_events", ["job_id", "id"])

    op.create_table(
        "crawl_results",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("job_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("final_url", sa.Text(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.String(length=120), nullable=True),
        sa.Column("content_length", sa.Integer(), nullable=True),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("fetch_mode", sa.String(length=10), nullable=False),
        sa.Column("elapsed_ms", sa.Integer(), nullable=True),
        sa.Column("redirects", sa.Integer(), nullable=False),
        sa.Column("body_ref", sa.String(length=64), nullable=True),
        sa.Column("error_kind", sa.String(length=40), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["crawl_jobs.id"],
            name=op.f("fk_crawl_results_job_id_crawl_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crawl_results")),
    )
    op.create_index("ix_crawl_results_job", "crawl_results", ["job_id"])

    op.create_table(
        "extracted_records",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("job_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("page_url", sa.Text(), nullable=False),
        sa.Column("extractor", sa.String(length=40), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("record_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["crawl_jobs.id"],
            name=op.f("fk_extracted_records_job_id_crawl_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extracted_records")),
        # Named, because the sink relies on it by name for ON CONFLICT - which
        # is what makes re-running a page idempotent (Phase 8's resume).
        sa.UniqueConstraint("job_id", "page_url", "record_hash", name="record_identity"),
    )


def downgrade() -> None:
    op.drop_table("extracted_records")
    op.drop_index("ix_crawl_results_job", table_name="crawl_results")
    op.drop_table("crawl_results")
    op.drop_index("ix_crawl_events_job_id", table_name="crawl_events")
    op.drop_table("crawl_events")
    op.drop_index("ix_crawl_jobs_claim", table_name="crawl_jobs")
    op.drop_table("crawl_jobs")
    op.drop_table("crawl_specs")
