"""extracted record sequence

Revision ID: 9ba18b485a37
Revises: 8f09ae124750
Create Date: 2026-09-03 00:58:48.707768
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "9ba18b485a37"
down_revision: str | None = "8f09ae124750"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Written by hand rather than taken from autogenerate, which produced a
    # NOT NULL column with no default: `autoincrement=True` is a hint to
    # SQLAlchemy's reflection, not DDL, and it generates nothing on a column
    # that is not a primary key. That version fails on a table with rows and
    # leaves no sequence when it succeeds.
    #
    # `GENERATED BY DEFAULT AS IDENTITY` matches what the model declares, so
    # a database built by `create_all` and one built by migrating agree.
    op.execute(
        "ALTER TABLE extracted_records "
        "ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL"
    )
    op.create_unique_constraint(op.f("uq_extracted_records_seq"), "extracted_records", ["seq"])


def downgrade() -> None:
    op.drop_constraint(op.f("uq_extracted_records_seq"), "extracted_records", type_="unique")
    op.drop_column("extracted_records", "seq")
